FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client curl

COPY package*.json ./

RUN npm cache clean --force
RUN npm install --only=dev

COPY . .   

EXPOSE 5000

USER node

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
CMD curl -f http://localhost:5000/health || exit 1

CMD ["npm","run", "dev"]


