FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client curl

COPY package*.json ./

RUN npm cache clean --force
RUN npm install

COPY . .   

RUN chown -R node:node /app

EXPOSE ${SERVER_PORT}

USER node

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
CMD curl -f http://localhost:${SERVER_PORT}/health || exit 1

CMD ["npm","run", "dev"]


